apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
        role: blue
    spec:
      containers:
      - name: todoapp-container
        image: docker-registry-login/todo-app:1.0.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      imagePullSecrets:
      - name: docker-registry-login
